### ISSUE TITLE
Question: Can I run with the `--tunnel` flag?

### ISSUE THREAD

**Issue by fabioknoedt** [DataDog/synthetics-ci-github-action#102]
Can I run with the `--tunnel` flag? If yes, how?
Thank you!

**Comment by peculiarism** [comment]
Hi @fabioknoedt, thank you for your question!

We do not support the tunnel with the GitHub Action today, but we will definitely keep this issue open alongside an internal feature request. If you could provide some additional information that would be great, namely: 

- What version of the GitHub Action are you running?
- Are you running a local server/environment that the GitHub Action can access? 
  - If yes, could you share more details on your setup?

If you could also provide additional information on the use case that would be really appreciated.

**Comment by fabioknoedt** [comment]
Hi @peculiarism! Thanks for the quick answer.

What version of the GitHub Action are you running?
**`v0.8.0`**

Are you running a local server/environment that the GitHub Action can access?
**Yes, I am deploying a local instance of my backend in the CI (using Minikube) and then right after that (in the same Github action machine) I try to run my Datadog tests.**

If yes, could you share more details on your setup?
**1. Start Minikube
2. Deploy all resources to Minikube (wait to be ready)
3. Test local application using `curl http://localhost/xxxx` (that works)
4. Run Datadog synthetic tests with `--tunnel` and pass the variable `BASE_URL=http://localhost`**

**Comment by fabioknoedt** [comment]
That's a great idea as it would leverage from the GHA cache. Thanks.
Let me try that and get back to you.

**Comment by Drarig29** [comment]
Closing, as a solution was posted in this issue.
