### ISSUE TITLE
Add documentation link for the format of a *.synthetics.json file

### ISSUE THREAD

**Issue by jensenbox** [DataDog/synthetics-ci-github-action#136]
I could not find the specification anywhere. It would be really helpful to link out or spec out the format that the file should be in.

I would love to be able to record it with the datadog interface or chrome extension and dump out to a synthetics.json file.

Thanks!

**Comment by Drarig29** [comment]
Hey again @jensenbox!

Thanks for the suggestion, we'll add the documentation link in the future.

For now, I'll give you the link directly:
https://docs.datadoghq.com/continuous_testing/cicd_integrations/configuration/#test-files

**Comment by Drarig29** [comment]
Closing this issue as we recently updated our readme with documentation links! 😄
