### ISSUE TITLE
Add failOnCriticalErrors and failOnMissingTests as inputs

### ISSUE THREAD

**Issue by IGx89** [DataDog/synthetics-ci-github-action#144]
Hi! Right now if I follow your first example, the job passes even if authorization fails due to failOnCriticalErrors defaulting to false. Could you add an input to this action to allow me to set failOnCriticalErrors to true? Adding failOnMissingTests would also be beneficial, since that also is defaulted to false and I would very much like the job to fail if someone accidentally deleted the synthetic!

Thanks!

**Comment by etnbrd** [comment]
Hey @IGx89 👋 

As you found out, we currently don't cover all the options as input parameters in the github action. Aligning all the parameters is on our roadmap, and we decided to prioritise to get to it faster. And we'll update and close this issue once we get there.

In the meantime, it's still possible to [configure these options in the global config file](https://github.com/DataDog/datadog-ci/tree/master/src/commands/synthetics#global-configuration-file-options).

Hope this helps.

Cheers

**Comment by Drarig29** [comment]
@IGx89 we added new inputs in [v0.14.0](https://github.com/DataDog/synthetics-ci-github-action/releases/tag/v0.14.0):

- `fail_on_critical_errors`
- `fail_on_missing_tests`
- `fail_on_timeout`

Closing the issue 😉
