### ISSUE TITLE
Test results aren't fetched

### ISSUE THREAD

**Issue by shalini171993** [DataDog/synthetics-ci-github-action#179]
Hi, 
I am using DataDog/synthetics-ci-github-action@v0.15.0 for triggering the datadog test. The workflow fails as the test has failed because of timeout and upon clicking Results_URL the below error message appears on the Datadog app page

"The CI result you are trying to access cannot be found.
It might not have been received yet. Please retry in a few moments."

![image](https://github.com/DataDog/synthetics-ci-github-action/assets/39578470/f1ae534d-e456-4be7-b3f3-279ea577656a)

The tests are continuously failing with time out issue. Can you please help with this?

**Comment by shalini171993** [comment]
Hey @Drarig29 ,
No the result isn't displayed even after trying later. It runs for 30 minutes( set default) but still couldn't fetch the results

**Comment by Drarig29** [comment]
@shalini171993 this doesn't seem like an issue with the GitHub Action itself, so I'm going to close this issue.

Please contact [our support](https://help.datadoghq.com/hc/en-us), so you can provide more information and get better help.
