### ISSUE TITLE
unable to use test_search_query with multiple tags

### ISSUE THREAD

**Issue by fuleinist** [DataDog/synthetics-ci-github-action#217]
The example given only provide 1 tag, tried to follow the syntax of `'key1:value1,key2:value2,....'` for multiple tags which seems does not work.

**Comment by Drarig29** [comment]
Hi @fuleinist! You should use exactly the same syntax as you would use to search tests in Datadog. So do not separate with commas, but with spaces :wink:

**Comment by Drarig29** [comment]
Closing the issue. Feel free to reopen if using spaces didn't fix your issue!
