### ISSUE TITLE
Node.js 16 actions are deprecated: datadog/synthetics-ci-github-action

### ISSUE THREAD

**Issue by brettcurtis** [DataDog/synthetics-ci-github-action#220]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: datadog/synthetics-ci-github-action@v0.24.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by Drarig29** [comment]
Hi! Thank you, we added this to our backlog. 🙇

**Comment by Drarig29** [comment]
Hi @brettcurtis! We released a new major version: [v1.0.0](https://github.com/DataDog/synthetics-ci-github-action/releases/tag/v1.0.0)

cc. @yizumi1012xxx since you reacted 😉
