### ISSUE TITLE
about workflow!

### ISSUE THREAD

**Issue by brinkqiang** [DataDog/synthetics-ci-github-action#249]
Hello, how is this function implemented in the following picture. I searched many places but couldn't find any information about how the workflow configure click interface template is generated

![workflows](https://github.com/DataDog/synthetics-ci-github-action/assets/10229072/147e63bb-564f-4c22-9812-60590b8c3188)

**Comment by Drarig29** [comment]
Hi @brinkqiang!

In our case, we created a starter workflow in the [actions/starter-workflows](https://github.com/actions/starter-workflows) repository:
- [`ci/datadog-synthetics.yml`](https://github.com/actions/starter-workflows/blob/main/ci/datadog-synthetics.yml)

Hope this helped, cheers! 😉
